// <auto-generated />
namespace CRMData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class V001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V001));
        
        string IMigrationMetadata.Id
        {
            get { return "201409051402472_V0.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
